### ISSUE TITLE
保存信息异常

### ISSUE THREAD

**Issue by fiblue** [myxzjie/cms#18]
![image](https://user-images.githubusercontent.com/99591072/163699083-19262ed3-7fba-4c8c-8b7c-30d6068290d5.png)

**Comment by unafraid-fearless** [comment]
g

**Comment by unafraid-fearless** [comment]
![image](https://github.com/myxzjie/cms/assets/36062846/27cc64a6-423b-4bb8-94e3-c5d87d66e2a7)
